# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

name: sample_app_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - -r requirements.txt
