version: 1.0

global:
  aws_region: us-west-2
  logs_dir: ./migration-logs
  num_threads: 4
  # s3_uri: s3://amzn-s3-demo-bucket # Must exist

source:
  all_databases: false
  databases:
    database1:
      - cpu
      - memory
    database2:

stage:
  #######################################################################
  # UNLOAD
  #######################################################################
  unload:
    # migration_tag: unload-YYYY-MM-DD-HH-mm-SS
    encryption: SSE_S3
    kms_key: null
    sns_topic_arn: null
    start_time: "2000-01-01 00:00:00"
    end_time:   "2026-01-01 00:00:00"
    partition: year
    export_format: PARQUET
    compression: NONE
    custom_partition_count: 99
    recent_first: false
    append_timestamps: true
    max_file_size: 78GB
    enable_dynamodb_logger: false
    field_delimiter: ","
    escaped_by: "\\"
    order_by_asc: false
    logs_dir: unload-logs

  #######################################################################
  # TRANSFORM
  #######################################################################
  transform:
    athena_database_name: default
    dimensions_to_fields: {}
    # dimensions_to_fields:
    #   database1:
    #     cpu:
    #       - hostname
    add_validation_field: true
    logs_dir: transform-logs

  #######################################################################
  # INGESTION
  #######################################################################
  ingest:
    influxdb_version: v2
    lines_per_batch: 5000
    io_multiplier: 5
    retries: 20
    precision: ns
    logs_dir: ingestion-logs
    continue_on_error: true

  #######################################################################
  # VALIDATION
  #######################################################################
  validation:
    logs_dir: validation-logs
