{
 "title": "InfluxDB V2 Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Invocations over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\nimport \"date\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> map(fn: (r) => {\n      attrs       = json.parse(data: bytes(v: r._value))\n      start_time  = time(v: attrs[\"gen_ai.event.start_time\"])\n      end_time    = time(v: attrs[\"gen_ai.event.end_time\"])\n      duration_s  = (int(v: end_time) - int(v: start_time)) / 1000000000\n      return {\n        _time:       r._time,\n        _field:      \"duration\",\n        _value:      duration_s,\n        agent_name:  attrs[\"gen_ai.agent.name\"],\n        operation:   attrs[\"gen_ai.operation.name\"],\n      }\n    })\n  |> filter(fn: (r) => r.operation == \"invoke_agent\")\n  |> group(columns: [\"agent_name\"])\n  |> aggregateWindow(\n       every: 1000ms,\n       fn: sum,\n       column: \"_value\",\n       createEmpty: true\n    )\n  |> filter(fn: (r) => exists r._value)\n  "
    }
   ]
  },
  {
   "title": "Total agent invocations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> group()\n  |> map(fn: (r) => {\n      attrs = json.parse(data: bytes(v: r._value))\n      return {\n        r with\n        span_id:      r.span_id,\n        agent_name: attrs[\"gen_ai.agent.name\"],\n        operation:   attrs[\"gen_ai.operation.name\"],\n      }\n    })\n  |> filter(fn: (r) => exists r.agent_name)\n  |> keep(columns: [\"span_id\", \"operation\", \"agent_name\"])\n  |> count(column: \"span_id\") \n"
    }
   ]
  },
  {
   "title": "Total processed tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\n\nfrom(bucket: \"mybucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => \n    r._measurement == \"spans\" and\n    r._field == \"attributes\" and\n    strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\"))\n|> group()\n|> map(fn: (r) => {\n    attrs = json.parse(data: bytes(v: r._value))\n    return {\n        _time: r._time,\n        total_tokens: int(v: attrs[\"gen_ai.usage.total_tokens\"])\n    }\n})\n|> sum(column: \"total_tokens\")\n"
    }
   ]
  },
  {
   "title": "Invocations by agent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> group()\n  |> map(fn: (r) => {\n      attrs = json.parse(data: bytes(v: r._value))\n      return {\n        r with\n        span_id:      r.span_id,\n        agent_name: attrs[\"gen_ai.agent.name\"],\n        operation:   attrs[\"gen_ai.operation.name\"],\n      }\n    })\n\n  |> filter(fn: (r) => exists r.agent_name)\n  |> keep(columns: [\"span_id\", \"operation\", \"agent_name\"])\n\n"
    }
   ]
  },
  {
   "title": "Token usage by agent",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> group()\n  |> map(fn: (r) => {\n      attrs = json.parse(data: bytes(v: r._value))\n      return {\n        r with\n        agent_name: attrs[\"gen_ai.agent.name\"],\n        input_tokens: attrs[\"gen_ai.usage.input_tokens\"],\n        output_tokens: attrs[\"gen_ai.usage.output_tokens\"],\n        model: attrs[\"gen_ai.request.model\"],\n      }\n    })\n\n  |> filter(fn: (r) => exists r.agent_name)\n  |> keep(columns: [\"agent_name\", \"input_tokens\", \"output_tokens\"])\n\n"
    }
   ]
  },
  {
   "title": "Avg response times",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\nimport \"date\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> map(fn: (r) => {\n      attrs       = json.parse(data: bytes(v: r._value))\n      start_time  = time(v: attrs[\"gen_ai.event.start_time\"])\n      end_time    = time(v: attrs[\"gen_ai.event.end_time\"])\n      duration_s  = (int(v: end_time) - int(v: start_time)) / 1000000000\n      return {\n        _time:       r._time,\n        _field:      \"duration\",\n        _value:      duration_s,\n        agent_name:  attrs[\"gen_ai.agent.name\"],\n        operation:   attrs[\"gen_ai.operation.name\"],\n      }\n    })\n  |> filter(fn: (r) => r.operation == \"invoke_agent\")\n  |> group(columns: [\"agent_name\"])\n  |> mean(column: \"_value\")\n  |> rename(columns: {_value: \"\"})\n\n"
    }
   ]
  },
  {
   "title": "Output TPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "tokens/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\nimport \"date\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> map(fn: (r) => {\n      attrs         = json.parse(data: bytes(v: r._value))\n      start_time    = time(v: attrs[\"gen_ai.event.start_time\"])\n      end_time      = time(v: attrs[\"gen_ai.event.end_time\"])\n      duration_s    = (int(v: end_time) - int(v: start_time)) / 1000000000\n      output_tokens = int(v: attrs[\"gen_ai.usage.output_tokens\"])\n      tokens_per_s  = output_tokens / duration_s\n\n      return {\n        model: attrs[\"gen_ai.request.model\"],\n        agent_name: attrs[\"gen_ai.agent.name\"],\n        operation: attrs[\"gen_ai.operation.name\"],\n        tokens_per_second: tokens_per_s,\n        duration: duration_s,\n        output_tokens: output_tokens,\n      }\n    })\n  |> filter(fn: (r) => r.operation == \"chat\" and exists r.output_tokens)\n  |> group(columns: [\"model\"])\n  |> keep(columns: [\"tokens_per_second\", \"model\"])\n  |> rename(columns: {tokens_per_second: \"\"})\n"
    }
   ]
  },
  {
   "title": "Token usage by model",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> group()\n  |> map(fn: (r) => {\n      attrs = json.parse(data: bytes(v: r._value))\n      return {\n        r with\n        input_tokens: attrs[\"gen_ai.usage.input_tokens\"],\n        output_tokens: attrs[\"gen_ai.usage.output_tokens\"],\n        model: attrs[\"gen_ai.request.model\"],\n      }\n    })\n  |> filter(fn: (r) => exists r.input_tokens)\n  |> keep(columns: [\"input_tokens\", \"output_tokens\", \"model\"])\n"
    }
   ]
  },
  { "title": "Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Tool invocations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> map(fn: (r) => {\n      attrs = json.parse(data: bytes(v: r._value))\n      return {\n        r with\n        span_id:   r.span_id,\n        tool_name:   attrs[\"gen_ai.tool.name\"],\n        status:      attrs[\"tool.status\"]\n      }\n    })\n  |> filter(fn: (r) => exists r.tool_name)\n  |> keep(columns: [\"span_id\", \"tool_name\"])\n  |> group(columns: [\"tool_name\"])\n  |> distinct(column: \"span_id\")\n  |> count(column: \"_value\")\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  },
  {
   "title": "Tool success rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"experimental/json\"\n\nfrom(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"spans\" and\n      r._field == \"attributes\" and\n      strings.containsStr(v: r._value, substr: \"gen_ai.event.end_time\")\n  )\n  |> map(fn: (r) => {\n      attrs = json.parse(data: bytes(v: r._value))\n      return {\n        r with\n        tool_name:   attrs[\"gen_ai.tool.name\"],\n        _value:      if attrs[\"tool.status\"] == \"success\" then 1.0 else 0.0\n      }\n    })\n  |> filter(fn: (r) => exists r.tool_name)\n  |> group(columns: [\"tool_name\"])\n  |> mean(column: \"_value\")\n  |> map(fn: (r) => ({ r with col: \"all\" }))\n  |> group()\n  |> pivot(rowKey: [\"col\"], columnKey: [\"tool_name\"], valueColumn: \"_value\")\n"
    }
   ]
  }
 ]
}